### ISSUE TITLE
Scalar reveals the secret value

### ISSUE THREAD

**Issue by RajeshRk18** [Toposware/cheetah#37]
Scalar reveals the limbs as the elements of Fixed size array implements Copy trait. Whenever they have to be moved, limbs are copied thus leaving the original array in memory until it is overwritten.

I have to change the scope of limbs to find this bug.

I have reproduced the issue here: https://gist.github.com/RajeshRk18/24b2f273ea689786c3bb5a19990c6166

## Expected Behaviour

For the scalar `Scalar([12, 34, 56, 78])`,
when the given code is run,
```
Creation Address: 0x7ffe0a86a4b8 
Value before dropping: [11246162368984329641, 15720856220356058543, 2654058533781523010, 95027734021429075]
Returned Address: 0x7ffe0a86a4b8 // same location means that limbs are not moved
Value at Returned Address: [0, 0, 0, 0]
Value at Creation Address: [0, 0, 0, 0]
```

## Actual Observed Behavior
```
Creation Address: 0x7ffe0a86a4b8 
Value before dropping: [11246162368984329641, 15720856220356058543, 2654058533781523010, 95027734021429075]
Returned Address: 0x7ffe0a86a470 // different location means that limbs are moved
Value at Returned Address: [0, 0, 0, 0]
Value at Creation Address: [11246162368984329641, 15720856220356058543, 2654058533781523010, 95027734021429075]
```

**Comment by Nashtare** [comment]
Hi! This is indeed an expected behavior for types that implement the `Copy` trait, for which dropping the value won't `zeroize` the original memory.

**Comment by RajeshRk18** [comment]
So, clearing the original memory doesn't matter because STARKs don't have a trapdoor?

**Comment by Nashtare** [comment]
I am not sure to understand your sentence.
This library is intended to provide a mid-level API of elliptic curve operations over a specific curve. If you intend to use it (which I don't recommend by the way as it is unmaintained, unless it is for academic/educative purposes), in a context where `Scalar` values have to remain secret, you can use a wrapper that doesn't implement `Copy`, and will properly wipe-out memory on `drop`.

**Comment by RajeshRk18** [comment]
> I am not sure to understand your sentence.
> This library is intended to provide a mid-level API of elliptic curve operations over a specific curve. If you intend to use it (which I don't recommend by the way as it is unmaintained, unless it is for academic/educative purposes), in a context where `Scalar` values have to remain secret, you can use a wrapper that doesn't implement `Copy`, and will properly wipe-out memory on `drop`.

As the description says that Cheetah is STARK friendly, I am just saying STARK has no trapdoor unlike traditional Cryptography which has a trapdoor in keys, signatures, etc. So, Scalar implements the Copy trait.

Yeah, if someone prefers to use Scalar as a secret, they can wrap the limb array with Box. **But, this must be mentioned somewhere.**

**Comment by Nashtare** [comment]
The `zeroize` crate is already fairly well documented on what guarantees it provides and which situations that may leave unwanted copies of your data in memory. If you want to use a higher-level abstraction, you can use the `secrecy` crate. Again, while you mention STARKs, this library is solely intended to provide on its own support for elliptic curve operations over the so-called `Cheetah` curve. It is not the purpose of this library, or any library for what it's worth, to describe the behavior of all its internal dependencies.
